Add new required `module_source_regex` to provider config, add new required `module_source` tag to `modtm_telemetry` resource
Azure/terraform-provider-modtm pull request #49
Opened 2024-10-20 09:23 UTC by lonegunmanb

Only telemetry with tag module_source that matches at least one of module_source_regex would be collected

2024-10-21 11:28 UTC, matt-FFFFFF requested changes

2024-10-24 09:01 UTC, lonegunmanb commented on internal/provider/telemetry_resource.go
> +		return
Is a telemetry event without source helpful to the telemetry consumer? @matt-FFFFFF

2024-10-24 11:24 UTC, matt-FFFFFF commented on internal/provider/telemetry_resource.go
> +		return
Good point, yes I wasn't thinking clearly.

2024-10-24 11:25 UTC, matt-FFFFFF approved these changes

2024-10-30 05:45 UTC, merged

2024-10-30 08:30 UTC, jaredfholgate commented on internal/provider/telemetry_resource.go
> +		return
Can't we still get the module name in this scenario and may categorise as `inner sourced`? I think if we can still get some data from it, that would be useful to understand the percentage of people forking our modules. E.g. the categories could be:

- `inner_source_local_file_system`
- `inner_source_git`
- `inner_source_other`

Quite possible I am missing something here, so apologies if I am am, but thought we still had the module name and version available maybe???

2024-10-30 08:32 UTC, jaredfholgate commented on internal/provider/telemetry_resource.go
> +		return
If you wanted to be super clever, you could extract and hash the first portion of the source uri and send that too, so we can tell if it is the same source. I think that might be verging on data we shouldn't store though?